### ISSUE TITLE
How is this JSON file maintained?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe-components#6]
If I do an `npm version patch` bump to a component, do I also need to submit a PR here? If the component URL includes a SHA1, I assume that a PR would be necessary.

Is it possible to update this repository automatically (after an initial PR to register the component) using NPM APIs and looking for an `aframe` subtree in `package.json`?

**Comment by ngokevin** [comment]
Discussion at https://github.com/aframevr/aframe-components/issues/5

But I think we'll leverage services such as unpkg.com (formerly NPM CDN) such that you can specify fuzzy version or fixed versions if you wish.
